services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: madlen-web
    environment:
      NODE_ENV: development
      # OpenTelemetry exporter will point at the Jaeger service (OTLP HTTP)
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      # Your OpenRouter key gets passed in from the host env or a .env file
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    ports:
      - "3000:3000"
    # Mount your code for hot reload; keep node_modules inside the container
    volumes:
      - .:/app
      - pnpm-store:/root/.pnpm-store
      - node_modules:/app/node_modules
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/jaeger:2.9.0 
    container_name: madlen-jaeger
    command:
      - --set
      - receivers.otlp.protocols.http.endpoint=0.0.0.0:4318
      - --set
      - receivers.otlp.protocols.grpc.endpoint=0.0.0.0:4317
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP

volumes:
  pnpm-store:
  node_modules:
